<?php

namespace P2;

/**
 * Each new term in the \Library\Fibonacci sequence is
 * generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * Sum: 44
 * By considering the terms in the \Library\Fibonacci sequence
 * whose values do not exceed four million, find the
 * sum of the even-valued terms.
 */
class EvenFibonacciNumbers extends \Library\Timer
{
    public function sumOfFibonacci($max)
    {
        $fib = 0;
        $sum = 0;
        for ($i = 0; $fib < $max; $i++) {
            $fib = (int)round(pow((sqrt(5) + 1) / 2, $i + 1) / sqrt(5));
            if ($fib >= $max) {
                break;
            }
            if ($fib % 2 === 0) {
                $sum += $fib;
            }
        }
        return $sum;
    }
}
